<?php
/** @var $block \AlexRyall\Slider\Block\Widget\Slider */
?>
<div class="slider-container" data-bind="scope: 'slider-<?php echo $block->getUniqueId() ?>'">
    <div id="slider-<?php echo $block->getUniqueId() ?>" class="slider" data-bind="afterRender:initSlick">
        <?php foreach ($block->getBanners() as $banner): ?>
            <div><?php echo $banner ?></div>
        <?php endforeach; ?>
    </div>
    <?php if ($block->getHasNav() == 'true'): ?>
    <div id="slider-nav-<?php echo $block->getUniqueId() ?>" class="slider-nav" data-bind="afterRender:initNavSlick">
        <?php foreach ($block->getBanners(true) as $banner): ?>
            <div><?php echo $banner ?></div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "slider-<?php echo $block->getUniqueId() ?>": {
                        "component": "AlexRyall_Slider/js/view/slider",
                        "config": {
                            "autoplay": <?= $block->getIsAutplay() ?>,
                            "speed": <?= $block->getSpeedInMs() ?>,
                            "rtl": <?= $block->getIsRtl() ?>,
                            "fade": <?= $block->getIsFade() ?>,
                            "slidesToShow": <?= $block->getSlidesToShow() ?>,
                            "slidesToScroll": <?= $block->getSlidesToScroll() ?>
                        }
                    }
                }
            }
        }
    }
</script>
